# Site
name: "JB's Corner"
description: "JB's Corner - Video Games - SteamDeck - Computer Science - Data Science"
logo: 'assets/images/logo.png'
favicon: 'assets/icons/favicon.ico'
baseurl: ''
disqus: 'JohnnyBlocks'
email: 'jb@JohnnyBlocks.com'
mailchimp-list: 'https://mailchi.mp/070704eeeaa2/corner-news-letter'

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    JohnnyBlocks:
      name:           JohnnyBlocks
      avatar:         assets/icons/JB.png
      tagline:        "Never Be Game Over"
      bio:            "I am JohnnyBlocks.  Never be Game Over!<br />Data Scientist : Computer Scientist : Video&nbsp;Gamer : Vegan"
      email:          jb+corner@JohnnyBlocks.com
      steam:          https://s.team/p/kcv-whdv
      github:         https://github.com/JohnnyBlocks
      reddit:         https://www.reddit.com/user/YoYo-Pete
      discord:        https://discordapp.com/users/121071541164310529
      #linkedin:       ''
      #twitter:        ''
      telegram:       https://telegram.me/JohnnyBlocks
      instagram:      https://instagram.com/JohnnyBlocks_
      youtube:        https://www.youtube.com/@JohnnyBlocks
      site:           https://JohnnyBlocks.com

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: JohnnyBlocks
      avatar: assets/icons/JB.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]